
project_id = "ocmqqtgcadltakzuwixd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:5173"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[db]
enabled = true
port = 54322

[storage]
enabled = true
port = 54323

[functions.parse-resume]
verify_jwt = false

[functions.search-candidates]
verify_jwt = false
